# Generated by Django 6.0.3 on 2026-03-05 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='lead_state',
        ),
    ]
