# Generated by Django 6.0.3 on 2026-03-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_interaction_options_alter_interaction_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_state',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal', 'Proposal sent'), ('won', 'Closed won'), ('lost', 'Closed lost')], default='new', max_length=20),
        ),
    ]
